// Generated By Chat GPT 4.0
using UnityEngine;

[RequireComponent(typeof(MeshRenderer))]
public class RainbowColorChanger : MonoBehaviour
{
    public float speed = 1.0f;
    private MeshRenderer meshRend;

    void Start()
    {
        meshRend = GetComponent<MeshRenderer>();
    }

    void Update()
    {
        float lerpTime = Mathf.PingPong(Time.time * speed, 1);
        meshRend.material.color = Color.HSVToRGB(lerpTime, 1, 1);
    }
}
