@startuml
package LowerBoard  {
    
    class Kaboo  {
        - hitPoints: 360
        - retractedHitPoints: 180
        + isRetracted: bool
        - Hit(): void
    }
    
    class BigKaboo{
      - hitPoints: 480
      + isRetracted: bool
      - Hit(): void
      - Retract(): void 
      + AllKaboosRetracted(Kaboo): void
    }
    
    class Gordow {
      - hitPoints: 240
    }
    
    class MummyBall{
      - hitsCount: 0
      - hitPoints: 360
      - defeatPoints: 8
      - Hit(): void 
      + Defeat(): void
    }
    
    class KirbySprite {
      + state: ExpressionState
      + ChangeExpression(): void
    }
    
    class WarpStar {
      + isActive: bool
      + Call(): void
      + Warp(): void
    }
    
    class Bumper {
      - hitPoints: 50
      - Hit(): void
    }
    
    class Inlane {
      - hitPoints: 10
      - Traverse(): void
    }
    
    class Outlane {
      - hitPoints: 200
      - Traverse(): void
    }
    
    class EnergyDrink {
      - hitPoints: 100
      - Hit(): void
      + Appear(): void
      + Remove(): void
    }
    
    class MaximTomato {
      + Appear(): void
      + Remove(): void
    }
    
    class StarLauncher {
      - isActive: bool
      + LaunchDirection: Direction
      + Launch(): void
    }
    
    enum ExpressionState {
      SLEEP,
      WAKE,
      DOWN
    }
    
    enum Direction {
      UP,
      DOWN,
      LEFT,
      RIGHT,
      CENTER
    }
    
    entity "Lower Board" as LowerBoard {
      + Kaboo 
      + BigKaboo
      + Gordow
      + MummyBall
      + KirbySprite
      + WarpStar
      + Bumper
      + Inlane
      + Outlane
      + EnergyDrink
      + MaximTomato
      + DrainStopper
      + StarLauncher
    }

    LowerBoard *-- Kaboo :  6 
    LowerBoard *-- BigKaboo :  1
    LowerBoard *-- Gordow : 5
    LowerBoard *-- MummyBall :  1
    LowerBoard *-- KirbySprite :  3
    LowerBoard *-- WarpStar :  1
    LowerBoard *-- Bumper :  2
    LowerBoard *-- Inlane :  2
    LowerBoard *-- Outlane :  2
    
    Kaboo--> BigKaboo:  <<modiefies>>
    BigKaboo --> StarLauncher:  <<modifies>>
    MummyBall --> WarpStar : <<calls>>
 
    KirbySprite --> MaximTomato
    KirbySprite --> EnergyDrink
    
     Inlane -> EnergyDrink : <<calls>>
    
    note top of KirbySprite : "Depending on the\nstate of the\nother KirbySprites,\nthe MaximTomato\nor DrainStopper\nwill be called\nwhen the\nKirbySprite\nchanges\nexpression."
    
    
    
    }
@enduml