//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.1
//     from Assets/Inputs/FipperActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @FipperActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @FipperActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""FipperActions"",
    ""maps"": [
        {
            ""name"": ""Flipper"",
            ""id"": ""870ebc11-77ab-41d6-9262-3b5f74943a7d"",
            ""actions"": [
                {
                    ""name"": "" Flipper Raise Left"",
                    ""type"": ""Value"",
                    ""id"": ""b24a7d12-4d45-4523-b230-123c19d78035"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Flipper Lower Left"",
                    ""type"": ""Button"",
                    ""id"": ""7d565c08-b295-4307-a77b-b7be39556410"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""615cfe51-1f0d-4bdf-bf92-852ad47108eb"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": "" Flipper Raise Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f62c1118-c812-48c5-86ed-62c1ec5561dd"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flipper Lower Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Flipper
        m_Flipper = asset.FindActionMap("Flipper", throwIfNotFound: true);
        m_Flipper_FlipperRaiseLeft = m_Flipper.FindAction(" Flipper Raise Left", throwIfNotFound: true);
        m_Flipper_FlipperLowerLeft = m_Flipper.FindAction("Flipper Lower Left", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Flipper
    private readonly InputActionMap m_Flipper;
    private List<IFlipperActions> m_FlipperActionsCallbackInterfaces = new List<IFlipperActions>();
    private readonly InputAction m_Flipper_FlipperRaiseLeft;
    private readonly InputAction m_Flipper_FlipperLowerLeft;
    public struct FlipperActions
    {
        private @FipperActions m_Wrapper;
        public FlipperActions(@FipperActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @FlipperRaiseLeft => m_Wrapper.m_Flipper_FlipperRaiseLeft;
        public InputAction @FlipperLowerLeft => m_Wrapper.m_Flipper_FlipperLowerLeft;
        public InputActionMap Get() { return m_Wrapper.m_Flipper; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FlipperActions set) { return set.Get(); }
        public void AddCallbacks(IFlipperActions instance)
        {
            if (instance == null || m_Wrapper.m_FlipperActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_FlipperActionsCallbackInterfaces.Add(instance);
            @FlipperRaiseLeft.started += instance.OnFlipperRaiseLeft;
            @FlipperRaiseLeft.performed += instance.OnFlipperRaiseLeft;
            @FlipperRaiseLeft.canceled += instance.OnFlipperRaiseLeft;
            @FlipperLowerLeft.started += instance.OnFlipperLowerLeft;
            @FlipperLowerLeft.performed += instance.OnFlipperLowerLeft;
            @FlipperLowerLeft.canceled += instance.OnFlipperLowerLeft;
        }

        private void UnregisterCallbacks(IFlipperActions instance)
        {
            @FlipperRaiseLeft.started -= instance.OnFlipperRaiseLeft;
            @FlipperRaiseLeft.performed -= instance.OnFlipperRaiseLeft;
            @FlipperRaiseLeft.canceled -= instance.OnFlipperRaiseLeft;
            @FlipperLowerLeft.started -= instance.OnFlipperLowerLeft;
            @FlipperLowerLeft.performed -= instance.OnFlipperLowerLeft;
            @FlipperLowerLeft.canceled -= instance.OnFlipperLowerLeft;
        }

        public void RemoveCallbacks(IFlipperActions instance)
        {
            if (m_Wrapper.m_FlipperActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IFlipperActions instance)
        {
            foreach (var item in m_Wrapper.m_FlipperActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_FlipperActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public FlipperActions @Flipper => new FlipperActions(this);
    public interface IFlipperActions
    {
        void OnFlipperRaiseLeft(InputAction.CallbackContext context);
        void OnFlipperLowerLeft(InputAction.CallbackContext context);
    }
}
