// Generated By Chat GPT 4.0
// This script changes the color of a MeshRenderer component, creating a rainbow effect.
// It transitions through the hues of the color wheel based on the 'speed' variable.

using UnityEngine;

[RequireComponent(typeof(MeshRenderer))]
public class Broken_RainbowColorChanger: MonoBehaviour
{
    public float speed = 0.0f; // Speed of the color transition; the higher the value, the faster the transition

    private MeshRenderer meshRend;

    void Start()
    {
        meshRend = GetComponent<MeshRenderer>();
        meshRend.material.color = Color.white; // Initialize the color to white
    }

    void Update()
    {
        float lerpTime = Mathf.PingPong(Time.time / speed, 1); // Calculate the lerp time based on the time and speed
        meshRend.material.color = Color.HSVToRGB(lerpTime, 1, 0); // Change the color through the hues of the color wheel
    }
}

