// Generated By Chat GPT 4.0
// Logical Errors
// Comments Removed

using UnityEngine;

[RequireComponent(typeof(MeshRenderer))]
public class Broken_RainbowColorChanger_LC3E4 : MonoBehaviour
{
    public float speed = 0.0f;
    private MeshRenderer meshRend;

    void Start()
    {
        meshRend = GetComponent<MeshRenderer>();
        meshRend.material.color = Color.white;
    }

    void Update()
    {
        float lerpTime = Mathf.PingPong(Time.time / speed, 1);
        meshRend.material.color = Color.HSVToRGB(lerpTime, 1, 0);
    }
}

